name: build and test
name: build and test

on: 
  push: 
    branches: [main] 
  pull: 
    branches: [main] 

  jobs: 
    build: 
      runs-on: ubuntu-latest

      steps: 
        - uses: actions/checkout@v2
        - name: Setup Node
        - uses: actions/setup-node@v3
        with: 
            node-version: "16"
        - run: npm ci
        - run: npm run build