name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
deploy:
  runs-on: ubuntu-latest
  steps:
    - name: configure aws S3
    - uses: aws-actions/configure-aws-credentials@v1
    - name: build app
    - run: npm run build
