name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
deploy:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  runs-on: ubuntu-latest
  steps:
    - name: configure aws S3
    - uses: aws-actions/configure-aws-credentials@v1
    - name: build the build
